name: first test

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: welcom message
      run : echo "hello frr"

    - name: list all files
      run : ls 

    - name: read 
      run : cat README.md