name: first test

on: push

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
    - name: job _1
      run : echo "hello frr from job 1" >> text.txt 
    
    - name: upload the text.txt 
      uses: actions/upload-artifact@v7
      with:
        name: test
        path: text.txt

  job_2:
    runs-on: ubuntu-latest 
    steps:

    - name: download the text.txt
      uses: actions/download-artifact@v8
      with:
        name: text,txt

    - name: job _2
      run : echo "im the job 2 i add this" >> text.txt 
  
  job_3:
    runs-on: ubuntu-latest
    steps:
    - name: download the text.txt
      uses: actions/download-artifact@v8
      with:
        name: text.txt
    - name: job _3
      run : cat text.txt