name: first test

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: welcom message
      run : echo "hello frr"

    - name: list all files before checkout 
      run : ls 

    - name: checkout the repo
      uses: actions/checkout@v3
    
    - name: list all files and read readme
      run : |
        chmod +x ascci-script.sh
        ascci-script.sh
        